### ISSUE TITLE
The app is crashing.

### ISSUE THREAD

**Issue by rakeshgopathi** [romainguy/elegant-underline#1]
On kitkat device 
 Process: com.android.elegantunderline, PID: 3768
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.elegantunderline/com.android.elegantunderline.MainActivity}: android.view.InflateException: Binary XML file line #12: Error inflating class com.android.elegantunderline.UnderlineView

**Comment by romainguy** [comment]
Please paste the entire stack trace so I can see what the actual cause of the crash is.

**Comment by rakeshgopathi** [comment]
The app crashed on an emulator running Android 4.4.2 and on a Xiaomi device running Android 4.4.4.
The underlines are not drawn with regions on devices running with API 22,23.(Nexus 6 emulators)
![screenshot_20160707-122037](https://cloud.githubusercontent.com/assets/16552376/16644879/b6be8ffa-443d-11e6-90b1-57bb62e281c3.png)
![screenshot_20160707-122101](https://cloud.githubusercontent.com/assets/16552376/16644880/b6bedd2a-443d-11e6-8612-f56d66fc985d.png)

This trace is from the xiaomi device.
07-07 12:12:13.029 6598-6598/com.android.elegantunderline E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.android.elegantunderline, PID: 6598
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.elegantunderline/com.android.elegantunderline.MainActivity}: android.view.InflateException: Binary XML file line #12: Error inflating class com.android.elegantunderline.UnderlineView
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2200)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5052)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                                at dalvik.system.NativeStart.main(Native Method)
                                                                             Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class com.android.elegantunderline.UnderlineView
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:623)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                                at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
                                                                                at android.app.Activity.setContentView(Activity.java:1940)
                                                                                at com.android.elegantunderline.MainActivity.onCreate(MainActivity.java:10)
                                                                                at android.app.Activity.performCreate(Activity.java:5242)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249) 
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:136) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5052) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                                at dalvik.system.NativeStart.main(Native Method) 
                                                                             Caused by: java.lang.reflect.InvocationTargetException
                                                                                at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:597)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                                at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290) 
                                                                                at android.app.Activity.setContentView(Activity.java:1940) 
                                                                                at com.android.elegantunderline.MainActivity.onCreate(MainActivity.java:10) 
                                                                                at android.app.Activity.performCreate(Activity.java:5242) 
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249) 
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:136) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5052) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                                at dalvik.system.NativeStart.main(Native Method) 
                                                                             Caused by: java.lang.NoSuchMethodError: android.view.View.<init>
                                                                                at com.android.elegantunderline.UnderlineView.<init>(UnderlineView.java:0)
                                                                                at com.android.elegantunderline.UnderlineView.<init>(UnderlineView.java:0)
                                                                                at com.android.elegantunderline.UnderlineView.<init>(UnderlineView.java:0)
                                                                                at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:597) 
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699) 
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                                at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290) 
                                                                                at android.app.Activity.setContentView(Activity.java:1940) 
                                                                                at com.android.elegantunderline.MainActivity.onCreate(MainActivity.java:10) 
                                                                                at android.app.Activity.performCreate(Activity.java:5242) 
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249) 
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:136) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5052) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                                                at dalvik.system.NativeStart.main(Native Method) 

This Trace is from the Emulator.

07-07 02:57:37.941 4231-4231/com.android.elegantunderline E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.android.elegantunderline, PID: 4231
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.elegantunderline/com.android.elegantunderline.MainActivity}: android.view.InflateException: Binary XML file line #12: Error inflating class com.android.elegantunderline.UnderlineView
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                                at dalvik.system.NativeStart.main(Native Method)
                                                                             Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class com.android.elegantunderline.UnderlineView
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:621)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                                at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
                                                                                at android.app.Activity.setContentView(Activity.java:1929)
                                                                                at com.android.elegantunderline.MainActivity.onCreate(MainActivity.java:10)
                                                                                at android.app.Activity.performCreate(Activity.java:5231)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:136) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                                at dalvik.system.NativeStart.main(Native Method) 
                                                                             Caused by: java.lang.reflect.InvocationTargetException
                                                                                at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:595)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697) 
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                                at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290) 
                                                                                at android.app.Activity.setContentView(Activity.java:1929) 
                                                                                at com.android.elegantunderline.MainActivity.onCreate(MainActivity.java:10) 
                                                                                at android.app.Activity.performCreate(Activity.java:5231) 
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:136) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                                at dalvik.system.NativeStart.main(Native Method) 
                                                                             Caused by: java.lang.NoSuchMethodError: android.view.View.<init>
                                                                                at com.android.elegantunderline.UnderlineView.<init>(UnderlineView.java:0)
                                                                                at com.android.elegantunderline.UnderlineView.<init>(UnderlineView.java:0)
                                                                                at com.android.elegantunderline.UnderlineView.<init>(UnderlineView.java:0)
                                                                                at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:595) 
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697) 
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:756) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                                at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290) 
                                                                                at android.app.Activity.setContentView(Activity.java:1929) 
                                                                                at com.android.elegantunderline.MainActivity.onCreate(MainActivity.java:10) 
                                                                                at android.app.Activity.performCreate(Activity.java:5231) 
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:136) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by romainguy** [comment]
Thanks. It's just calling a constructor that didn't exist on KitKat.

**Comment by rr0055256** [comment]
Hi Romain - I'm having the same issue while running this on KitKat. What is the solution ?
